-- MySQL Script generated by MySQL Workbench
-- Mon Mar 14 11:40:03 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Proveedor` (
  `idProveedor` INT NOT NULL,
  `razon_social` MEDIUMINT(15) NULL,
  `direccion` VARCHAR(45) NULL,
  `telefono` MEDIUMINT(15) NOT NULL,
  `representante` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`idProveedor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Producto` (
  `idproductos` INT NOT NULL,
  `Precio_idPrecio` INT NOT NULL,
  `descripcion` VARCHAR(80) NULL,
  `precio_venta` FLOAT NULL,
  `marca` VARCHAR(45) NULL,
  `Proveedor_idProveedor` INT NOT NULL,
  `telefono` MEDIUMINT(10) NULL,
  PRIMARY KEY (`idproductos`, `Precio_idPrecio`, `Proveedor_idProveedor`),
  INDEX `fk_Producto_Proveedor1_idx` (`Proveedor_idProveedor` ASC) VISIBLE,
  CONSTRAINT `fk_Producto_Proveedor1`
    FOREIGN KEY (`Proveedor_idProveedor`)
    REFERENCES `mydb`.`Proveedor` (`idProveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`sucursal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`sucursal` (
  `idsucursal` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `telefono_idtelefono` INT NOT NULL,
  PRIMARY KEY (`idsucursal`, `telefono_idtelefono`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Inventario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Inventario` (
  `idinventario` INT NOT NULL,
  `sucursal_idsucursal` INT NOT NULL,
  `Producto_idproductos` INT NOT NULL,
  `Stock` MEDIUMINT(4) NULL,
  `fecha_ingreso` DATE NULL,
  PRIMARY KEY (`idinventario`, `sucursal_idsucursal`, `Producto_idproductos`),
  INDEX `fk_Inventario_sucursal_idx` (`sucursal_idsucursal` ASC) VISIBLE,
  INDEX `fk_Inventario_Producto1_idx` (`Producto_idproductos` ASC) VISIBLE,
  CONSTRAINT `fk_Inventario_sucursal`
    FOREIGN KEY (`sucursal_idsucursal`)
    REFERENCES `mydb`.`sucursal` (`idsucursal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Inventario_Producto1`
    FOREIGN KEY (`Producto_idproductos`)
    REFERENCES `mydb`.`Producto` (`idproductos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Empleado` (
  `idEmpleados` INT NOT NULL,
  `nombre` VARCHAR(30) NULL,
  `dni` MEDIUMINT(9) NULL,
  `fecha_ingreso` DATE NULL,
  `sucursal_idsucursal` INT NOT NULL,
  `telefono` MEDIUMINT(10) NULL,
  PRIMARY KEY (`idEmpleados`, `sucursal_idsucursal`),
  INDEX `fk_Empleado_sucursal1_idx` (`sucursal_idsucursal` ASC) VISIBLE,
  CONSTRAINT `fk_Empleado_sucursal1`
    FOREIGN KEY (`sucursal_idsucursal`)
    REFERENCES `mydb`.`sucursal` (`idsucursal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Direccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Direccion` (
  `idDomicilio` INT NOT NULL,
  `Empleado_idEmpleados` INT NOT NULL,
  `direccion` VARCHAR(45) NULL,
  `codigo_postal` MEDIUMINT(9) NULL,
  `ciudad` VARCHAR(45) NULL,
  `Proveedor_idProveedor` INT NOT NULL,
  `sucursal_idsucursal` INT NOT NULL,
  PRIMARY KEY (`idDomicilio`, `Empleado_idEmpleados`, `Proveedor_idProveedor`, `sucursal_idsucursal`),
  INDEX `fk_Domicilio_Empleado1_idx` (`Empleado_idEmpleados` ASC) VISIBLE,
  INDEX `fk_Direccion_Proveedor1_idx` (`Proveedor_idProveedor` ASC) VISIBLE,
  INDEX `fk_Direccion_sucursal1_idx` (`sucursal_idsucursal` ASC) VISIBLE,
  CONSTRAINT `fk_Domicilio_Empleado1`
    FOREIGN KEY (`Empleado_idEmpleados`)
    REFERENCES `mydb`.`Empleado` (`idEmpleados`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Direccion_Proveedor1`
    FOREIGN KEY (`Proveedor_idProveedor`)
    REFERENCES `mydb`.`Proveedor` (`idProveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Direccion_sucursal1`
    FOREIGN KEY (`sucursal_idsucursal`)
    REFERENCES `mydb`.`sucursal` (`idsucursal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Precio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Precio` (
  `idPrecio` INT NOT NULL,
  `Producto_idproductos` INT NOT NULL,
  `importe` FLOAT(20) NULL,
  `iva` FLOAT(20) NULL,
  `fecha_actualizado` DATE NULL,
  PRIMARY KEY (`idPrecio`, `Producto_idproductos`),
  INDEX `fk_Precio_Producto1_idx` (`Producto_idproductos` ASC) VISIBLE,
  CONSTRAINT `fk_Precio_Producto1`
    FOREIGN KEY (`Producto_idproductos`)
    REFERENCES `mydb`.`Producto` (`idproductos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
